### ISSUE TITLE
Ufak bi fikir

### ISSUE THREAD

**Issue by furkanesenn** [dolpsoft/odessa#1]
node_modules'i repo ya koymak biraz saçma geldi bana, package.json dan zaten direkt indirebilirler. --save-dev ve --save flaglarıyla yaparsan

**Comment by rotten-kozanoglu** [comment]
> node_modules'i repo ya koymak biraz saçma geldi bana, package.json dan zaten direkt indirebilirler. --save-dev ve --save flaglarıyla yaparsan

onlar halledilecek, şu an hâlen daha geliştirilme aşamasında ve öyle şeyleri görmezden geliyoruz. yayımlamadan kısa bir süre önce onları düzenleyeceğiz!

**Comment by furkanesenn** [comment]
sey. geliştirilme aşamasında yapılması gereken bi şeydi zaten ama neyse

**Comment by rotten-kozanoglu** [comment]
> sey. geliştirilme aşamasında yapılması gereken bi şeydi zaten ama neyse

lan s1kt1r g1t

**Comment by dolpsoft** [comment]
> node_modules'i repo ya koymak biraz saçma geldi bana, package.json dan zaten direkt indirebilirler. --save-dev ve --save flaglarıyla yaparsan

düzeltildi
